### ISSUE TITLE
Add 'Save' option ?

### ISSUE THREAD

**Issue by kupiqu** [agateau/nanonote#9]
While I am aware that this is not the main purpose of nanonote, it would be good to have a save option, which would still be better if it would act on current selection (if any), or the entire content otherwise.

One use case related to this would be using nanonote to making a pile of ideas/thoughts/ToDo's/etc. At some point, one may want to save one of those entries to a file to work on it more specifically.

One can certainly do this manually, but it would be more efficient to have an option to save content/selection from within nanonote.

**Comment by agateau** [comment]
Hi, thanks for your suggestion, but it does not fit well with my idea of keeping Nanonote minimalist.

As you said, what you want to do can easily be done with a copy-and-paste: if you want to keep a part of your notes in a separate text file, I think it is more efficient to paste the selected text in a text editor, work on it from there and then save it, instead of saving it from Nanonote and reopening it from your text editor.
